[package]
name = "cryp-com-br"
version = "0.1.0"
authors = ["willyrgf <willyr.goncalves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
